title: "Aleksandra Conevska"
email: "aleksandraconevska@fas.harvard.edu"
description: >-
Aleksandra Conevska 

baseurl: "" 
url: "https://aleksandraconevska.github.io"

theme: minima

markdown: kramdown
plugins:
  - jekyll-feed

nav:
  - name: "Home"
    link: /
  - name: "About"
    link: /about
  - name: "CV"
    link: /cv/cv_conevska.pdf
