title: "Aleksandra Conevska"
email: "aleksandraconevska@fas.harvard.edu"
description: >-
     

url: "https://aleksandraconevska.com"
baseurl: ""

markdown: kramdown
plugins:
  - jekyll-feed

nav:
  - name: "Research"
    link: /Research
  - name: "CV"
    link: /CV/cv_conevska.pdf
  - name: "Teaching"
    #link: /teaching
