title: "Aleksandra Conevska"
link: https://aconevska.github.io/website/

email: "aleksandraconevska@fas.harvard.edu"
description: >-
     

baseurl: "/"
url: "https://aconevska.github.io"

markdown: kramdown
plugins:
  - jekyll-feed

nav:
  - name: "research"
    link: /research
  - name: "cv"
    link: /cv/cv_conevska.pdf
  - name: "teaching"
    link: /teaching
