title: "Aleksandra Conevska"
email: "aleksandraconevska@fas.harvard.edu"
description: >-
     

baseurl: "/"
url: "https://aconevska.github.io"

theme: minima

markdown: kramdown
plugins:
  - jekyll-feed

nav:
  - name: "Aleksandra Conevska"
    link: /
  - name: "Research"
    link: /research
  - name: "CV"
    link: /cv/cv_conevska.pdf
