name: Build CV PDF

on:
  push:
    paths:
      - 'cv/*.tex'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv/cv_conevska.tex
          latexmk_use_xelatex: true

      - name: Commit PDF
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add cv/cv_conevska.pdf
          git commit -m "Rebuild CV PDF"
          git push
